# Generated by Django 4.2.2 on 2023-08-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='excert',
            new_name='excerpt',
        ),
    ]
